name        : libiec61883
version     : 1.2.0
release     : 2
source      :
    - http://www.kernel.org/pub/linux/libs/ieee1394/libiec61883-1.2.0.tar.gz : 594dbdd4e391d8a4df740db573681b288eee0366e443e5d465febbefd24a5a32
homepage    : http://www.dennedy.org/libiec61883/
license     : GPL-2.0
component   :
    - multimedia.library
    - devel: programming.devel
    - utils: multimedia.library
summary     :
    - Firewire stream transmission
    - devel: Development files for libiec61883
    - utils: Command line utilities for libiec61883
description :
    - An implementation of the most relevant parts of IEC 61883 over libraw1394 for transmission, reception, and management of media streams and devices such as DV, MPEG2-TS, audio, and MIDI.
    - devel: Development files for libiec61883
    - utils: Command line utilities for libiec61883
patterns    :
    - utils:
        - /usr/bin
        - /usr/share/man
builddeps   :
    - pkgconfig(libraw1394)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
